#!/usr/bin/env bash
#
# This file is part of REANA.
# Copyright (C) 2026 CERN.
#
# REANA is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

set -o errexit
set -o nounset

BINARY_NAME=reana-datastore-s3fs
GO_PACKAGES=(./cmd/... ./internal/...)
VERSION=${VERSION:-$(git describe --tags --always --dirty 2>/dev/null || echo "dev")}
LDFLAGS="-s -w -X github.com/reanahub/reana-datastore-s3fs/internal/version.Version=${VERSION}"

docker_build() {
    docker build -t docker.io/reanahub/reana-datastore-s3fs .
}

docker_test() {
    docker run -i --rm docker.io/reanahub/reana-datastore-s3fs --version
}

format_go() {
    formatted=$(go fmt "${GO_PACKAGES[@]}")
    go mod tidy
    if [[ -n "$formatted" ]]; then
        echo "Go source files were not properly formatted. Please run './run-tests.sh --format-go' locally."
        echo "$formatted"
        exit 1
    fi
    if git rev-parse --is-inside-work-tree >/dev/null 2>&1 && ! git diff --quiet -- go.mod go.sum; then
        echo "Go module files were not properly formatted. Please run './run-tests.sh --format-go' locally."
        git diff -- go.mod go.sum
        exit 1
    fi
}

format_prettier() {
    prettier -c .
}

format_shfmt() {
    shfmt -d .
}

go_build() {
    CGO_ENABLED=0 go build \
        -trimpath \
        -ldflags "$LDFLAGS" \
        -o "$BINARY_NAME" \
        ./cmd/reana-datastore-s3fs
}

go_build_all() {
    mkdir -p dist
    CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build \
        -trimpath \
        -ldflags "$LDFLAGS" \
        -o "dist/${BINARY_NAME}-linux-amd64" \
        ./cmd/reana-datastore-s3fs
    CGO_ENABLED=0 GOOS=linux GOARCH=arm64 go build \
        -trimpath \
        -ldflags "$LDFLAGS" \
        -o "dist/${BINARY_NAME}-linux-arm64" \
        ./cmd/reana-datastore-s3fs
}

go_tests() {
    go test -coverprofile coverage.txt "${GO_PACKAGES[@]}"
}

lint_commitlint() {
    from=${2:-master}
    to=${3:-HEAD}
    pr=${4:-[0-9]+}
    if command -v commitlint >/dev/null 2>&1; then
        commitlint --from="$from" --to="$to"
    else
        npx commitlint --from="$from" --to="$to"
    fi
    found=0
    while IFS= read -r line; do
        commit_hash=$(echo "$line" | cut -d ' ' -f 1)
        commit_title=$(echo "$line" | cut -d ' ' -f 2-)
        commit_number_of_parents=$(git rev-list --parents "$commit_hash" -n1 | awk '{print NF-1}')
        # (i) skip checking release commits generated by Release Please
        if [ "$commit_number_of_parents" -le 1 ] && echo "$commit_title" | grep -qE "^chore\(.*\): release"; then
            continue
        fi
        # (ii) check presence of PR number
        if ! echo "$commit_title" | grep -qE "\(#$pr\)$"; then
            echo "ERROR: Headline does not end by '(#$pr)' PR number: $commit_title"
            found=1
        fi
        # (iii) check absence of merge commits in feature branches
        if [ "$commit_number_of_parents" -gt 1 ]; then
            if echo "$commit_title" | grep -qE "^chore\(.*\): merge "; then
                break # skip checking maint-to-master merge commits
            else
                echo "ERROR: Merge commits are not allowed in feature branches: $commit_title"
                found=1
            fi
        fi
    done < <(git log "$from..$to" --format="%H %s")
    if [ $found -gt 0 ]; then
        exit 1
    fi
}

lint_goaudit() {
    go install honnef.co/go/tools/cmd/staticcheck@latest
    go install golang.org/x/vuln/cmd/govulncheck@latest
    go mod verify
    go vet "${GO_PACKAGES[@]}"
    staticcheck "${GO_PACKAGES[@]}"
    govulncheck "${GO_PACKAGES[@]}"
}

lint_hadolint() {
    docker run -i --rm docker.io/hadolint/hadolint:v2.12.0 <Dockerfile
}

lint_jsonlint() {
    find . -name "*.json" -exec jsonlint -q {} \+
}

lint_markdownlint() {
    markdownlint-cli2 "**/*.md"
}

lint_shellcheck() {
    find . -name "*.sh" -exec shellcheck {} \+
}

lint_yamllint() {
    yamllint .
}

all() {
    docker_build
    docker_test
    format_go
    format_prettier
    format_shfmt
    go_build
    go_build_all
    go_tests
    lint_commitlint
    lint_goaudit
    lint_hadolint
    lint_jsonlint
    lint_markdownlint
    lint_shellcheck
    lint_yamllint
}

help() {
    echo "Usage: $0 [options]"
    echo "Options:"
    echo "  --all                Perform all checks [default]"
    echo "  --docker-build       Check Docker build"
    echo "  --docker-test        Check Docker test"
    echo "  --format-go          Check formatting of Go code"
    echo "  --format-prettier    Check formatting of Markdown etc files"
    echo "  --format-shfmt       Check formatting of shell scripts"
    echo "  --go-build           Build Go executable"
    echo "  --go-build-all       Build Linux amd64 and arm64 executables"
    echo "  --go-tests           Check Go test suite"
    echo "  --help               Display this help message"
    echo "  --lint-commitlint    Check linting of commit messages"
    echo "  --lint-goaudit       Check linting of Go code"
    echo "  --lint-hadolint      Check linting of Dockerfiles"
    echo "  --lint-jsonlint      Check linting of JSON files"
    echo "  --lint-markdownlint  Check linting of Markdown files"
    echo "  --lint-shellcheck    Check linting of shell scripts"
    echo "  --lint-yamllint      Check linting of YAML files"
}

if [ $# -eq 0 ]; then
    all
    exit 0
fi

arg="$1"
case $arg in
--all) all ;;
--help) help ;;
--docker-build) docker_build ;;
--docker-test) docker_test ;;
--format-go) format_go ;;
--format-prettier) format_prettier ;;
--format-shfmt) format_shfmt ;;
--go-build) go_build ;;
--go-build-all) go_build_all ;;
--go-tests) go_tests ;;
--lint-commitlint) lint_commitlint "$@" ;;
--lint-goaudit) lint_goaudit ;;
--lint-hadolint) lint_hadolint ;;
--lint-jsonlint) lint_jsonlint ;;
--lint-markdownlint) lint_markdownlint ;;
--lint-shellcheck) lint_shellcheck ;;
--lint-yamllint) lint_yamllint ;;
*) echo "[ERROR] Invalid argument '$arg'. Exiting." && help && exit 1 ;;
esac
